apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-count-data
          persistentVolumeClaim:
            claimName: log-output-pingpong-pvc
      containers:
      - name: ping-pong
        image: sericy/ping-pong
        volumeMounts:
          - name: shared-count-data
            mountPath: /usr/src/app/data
